version: '3'
services:
  db:
    image: postgres:11.6-alpine
    restart: always
    volumes:
      - ./containers/db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      TZ: Asia/Tokyo
    container_name: db
  app:
    build:
      context: .
    volumes:
      - .:/var/src/app
    ports:
      - '80:3000'
    environment:
      RAILS_ENV: development
      PG_DATABASE: postgres
      PG_PASSWORD: pass
      PG_USER: postgres
    links:
      - db
      - node
    working_dir: /var/src/app
    command: /bin/sh -c "rm -f /var/src/app/tmp/pids/server.pid;bundle exec rails s -b 0.0.0.0"
    cap_add:
      - ALL  # Add all privilege
    container_name: app
    tty: true
    stdin_open: true
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
  node:
    build:
      context: frontend
    working_dir: /var/src/app
    volumes:
      - ./frontend:/var/src/app:delegated
      - /var/src/app/node_modules
    ports:
      - 9090:8080
#    command: ./node_modules/.bin/webpack-dev-server --host 0.0.0.0 --inline --progress --public 0.0.0.0:9090 --config build/webpack.dev.conf.js
    command: yarn serve
    container_name: node
